### ISSUE TITLE
ib/command.c:4:10: 致命错误：lib/re.h：没有那个文件或目录

### ISSUE THREAD

**Issue by Yo-yo-ooo** [jjwang/HanOS#1]
ib/command.c:4:10: 致命错误：lib/re.h：没有那个文件或目录

**Comment by jjwang** [comment]
I am guessing that you are compiling userspace shell app which is placed in userspace folder.

The <lib/re.h> is used for string matching of command line interface. It is a soft link which is placed in lib folder. Please check whether the soft links are created correctly or not. If there are some problems on your computer, you can also copy the correspnding files from kernel folder.
